TitleLabel = "Chrome Updater"
TabMainLabel = "Main"
TabSettingLabel  = "Setting"
InstallLabel = "Path"
BranchLabel = "Branch"
NowVerLabel = "Current Version"
LatestVerLabel = "Latest Version"
FileSizeLabel = "File Size"
DownLoadChannelLabel = "Download Channel"
DownLoadedProcessMsg = "Download completed, file size: %s, verification file SHA1..."
InstalledMsg = "The installation is complete"
DownloadFailedMsg = "Download failed, please try again later"
Download95Msg = "The file SHA1 verification passed, start decompression and installation..."
DownloadNotStartedMsg = "Download did not start"
DownloadingMsg = "Downloading...%.2f MB / %s"
CheckBtnLabel = "Check"
InstallBtnLabel = "Update"
NoNeedUpdateMsg = "It is currently the latest version, no need to update!"
ChromeRunningMsg = "Chrome is running, please close and try again!"
ChromeUpdateRunningMsg = "Automatic update is being performed, please try again later!"
FirstInstallMsg = "Chrome is not detected in the current folder. Do you want to initialize the installation?"
StableVerOption = "STABLE"
BetaVerOption = "BETA"
DevVerOption = "DEV"
CanaryVerOption = "CANARY"
VersionSelectPlaceHolder = "Select one"
UpdateErrMsg = "Update failed, please check network or proxy settings"
PlusDownloadedMsg = "Download completed, start decompression and installation..."
PlusDownloadingMsg = "Downloading..."
MarkdownMsg = """
### Warning

---

* The original version of Shuax has stopped updating. The final version is **v1.5.2**, and the original repo has been deleted. Please refer to [Fork branch](https://github.com/libsgh/chrome_plus).
* [Bush2021](https://github.com/Bush2021/chrome_plus) is actively updating the maintainer, and the code is open source on GitHub.
* Please judge the security of Chrome++ by yourself, and solve common problems caused by Chrome++ by yourself."""
BaseSettingLabel = "Base"
ThemeLabel = "Theme"
LangLabel = "Lang"
AboutLabel = "About"
VersionLabel = "Version"
IssuesLabel = "Issues"
OfflinePkgLabel = "Web Service"
SystemOption = "System"
ThemeLightOption = "Light"
ThemeDarkOption = "Dark"
BaseRemainInstallFiles = "Remain install files"
BaseRemainHistoryFiles = "Remain history files"
UpdaterCheckBtnLabel = "New"
BaseGhProxy = "GitHub Proxy"
SystemTrayShowMenu = "Show"
SystemTrayHideMenu = "Hide"
SystemTrayAutoUpdateMenu = "Auto Update"
DialogTooltipTitle = "Tooltip"
DialogConfirmLabel = "OK"
DialogCloseLabel = "Close"
AutoUpdateProgress = "Auto-updating..."