TitleLabel = "Chrome更新器"
TabMainLabel = "主程序"
TabSettingLabel  = "设置"
InstallLabel = "安装目录"
BranchLabel = "版本分支"
NowVerLabel = "当前版本"
LatestVerLabel = "最新版本"
FileSizeLabel = "文件大小"
DownLoadChannelLabel = "下载通道"
DownLoadedProcessMsg = "下载完成, 文件大小: %s, 校验文件SHA1..."
InstalledMsg = "安装完成"
DownloadFailedMsg = "下载失败，请稍后重试"
Download95Msg = "文件SHA1校验通过, 开始解压安装..."
DownloadNotStartedMsg = "下载未开始"
DownloadingMsg = "下载中...%.2f MB / %s"
CheckBtnLabel = "检查更新"
InstallBtnLabel = "下载安装"
NoNeedUpdateMsg = "当前已是最新版本, 无需更新!"
ChromeRunningMsg = "Chrome正在运行, 请关闭后重试!"
FirstInstallMsg = "当前文件夹未检测到Chrome, 是否初始化安装?"
StableVerOption = "STABLE 稳定版"
BetaVerOption = "BETA 测试版"
DevVerOption = "DEV 开发版"
CanaryVerOption = "CANARY 金丝雀"
VersionSelectPlaceHolder = "请选择"
CheckErrMsg = "查询失败, 稍后重试"
PlusDownloadedMsg = "下载完成, 开始解压安装..."
PlusDownloadingMsg = "下载中..."
MarkdownMsg = """
### 说明

---

* Shuax原版已停止更新, 最终版本为**v1.5.2**, 并且原仓库已删除, 可参考[Fork分支](https://github.com/libsgh/chrome_plus).
* [Bush2021](https://github.com/Bush2021/chrome_plus)是正在活跃更新的维护者, 且代码在Github开源.
* 请自行鉴别Chrome++的安全性, 由于Chrome++产生的各类问题自行解决.<br>"""
BaseSettingLabel = "基础设置"
ThemeLabel = "主题"
LangLabel = "语言"
AboutLabel = "关于"
VersionLabel = "当前版本"
IssuesLabel = "意见反馈"
OfflinePkgLabel = "离线安装包"
SystemOption = "System"
ThemeLightOption = "Light"
ThemeDarkOption = "Dark"
BaseRemainInstallFiles = "保留安装文件"
BaseRemainHistoryFiles = "保留历史版本"
UpdaterCheckBtnLabel = "有更新"
BaseGhProxy = "GitHub代理, 为空将直连"

